language: node_js
node_js:
- "io.js"
- "0.12"
- "0.10"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dc42be257c956519b649
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
